name: Build Modpacks
on:
  pull_request:
    branches:
      - main
      - develop
    types: [closed]

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3

      - name: Download ModPackager
        run: |
          gh release download --repo SoapboxRaceWorld/ModPackager v2.1.0 -p "release_unix.zip" -O /tmp/modpackager
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Extract ModPackager
        run: | 
          unzip -j "/tmp/modpackager/release_unix.zip" "release_unix/*" -d "./modpackager"

      - name: Check what we got
        run: ls -R
