name: Build Modpacks
on:
  pull_request:
    branches:
      - main
      - develop
    types: [closed]

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3

      - name: Download ModPackager
        run: |
          gh release download \
          --repo SoapboxRaceWorld/ModPackager v2.1.0 \
          -p "release_unix.zip" \
          -O /tmp/release_unix.zip
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Extract ModPackager
        run: | 
          unzip -j "/tmp/release_unix.zip" "release_unix/*" \
          -d "./modpackager"

      - name: Check what we got
        run: ls -R

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101

      - name: Build the thing!
        run: |
          chmod +x ./modpackager/ModPackager && \
          bash ./build.sh

      - name: Check again what we got
        run: ls -R

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: |
            ./output/*
            !./output/README.md
